name: 'Trigger'
on:
  push:
    branches:
      - feature/TD-210-initial-setup

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
